name: Building

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Installing requirements for App
        run:  |
          pip3 install -r requirements.txt
          echo "All requirements were successfully installed!"

      - name: Clone Buildozer Repo
        run: |
          git clone https://github.com/kivy/buildozer.git
          echo "Repo was successfully cloned!" 
              
      - name: Install dependencies
        run:  |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-13-jdk 
          sudo apt install python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev 
          sudo apt install libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade Cython==0.29.19 virtualenv
          echo "All dependencies were successfully installed!"
          
        
      - name: Installing Buildozer
        run:  |
          cd buildozer
          sudo python3 setup.py install
          cd ..
          echo "Buildozer was successfully installed!" 

      - name: Building Apk
        run:  | 
          python3 ch_version.py
          buildozer android release 
          echo "The Application was successfully built!"
        
      - name: Deliver the app
        env:
          text: "Report:⠀App⠀was⠀successfully⠀built"
        run:  |
          python3 delivery.py ${{ secrets.TOKEN }}
          python3 notification_manager.py ${{ secrets.TOKEN }} ${{ secrets.CHAT_ID }} $text
          echo "Apk was successfully delivered"

          
        
        
        
        
  

